[build]
  publish = "."
  command = ""

[[headers]]
  for = "/assets/videos/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/figures/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/paper/*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=3600"
